Функции для тренировки
htmlacademy-javascript/2180451-kekstagram-28 pull request #2
Opened 2023-02-16 14:00 UTC by Dante01Rus

2023-02-17 09:28 UTC, pavel-nyukalo requested changes

2023-02-17 09:28 UTC, pavel-nyukalo commented on index.html
> +  <script src="/js/functions.js"></script>
На опубликованной версии не сработает такой код. Надо либо `./js/...`, либо просто `js/...`

2023-02-17 09:28 UTC, pavel-nyukalo commented on js/functions.js
> +getStringLength(true, 4);
1. `string` += '' можно заменить на приведение к строке при помощи `String()`. Более наглядно может быть
2. Возвращать нужно просто `true/fasle`, поскольку эта функция нам еще пригодится при валидации. И в таком случае строки будут бесполезны. А в примере это просто пояснения, почему должно вернуться `true/false`
3. Соответственно, возращать можно просто результат сравнения и если еще заменить на `String`, то код может сократиться до такого
```js
function getStringLength (string, length) {
  return String(string).length <= length
}
```
(еще можно над названиями переменных поработать, чтобы не запутаться)
Например
```js
function getStringLength (stringValue, maxLength) {
  return String(stringValue).length <= maxLength
}
``

2023-02-17 09:28 UTC, pavel-nyukalo commented on js/functions.js
> +
1. Аналогично про возврат функции. Она должна возвращать `true/false`
2. За счет того, что на 16 строке идет присваивание, а не сравнение (для чего и используется тернарник), то функция возвращает `'true - строка является палиндромом'` всегда

![image](https://user-images.githubusercontent.com/52506235/219604630-2dab1fac-26f7-463b-aec7-ff086f2cddab.png)

Если кстати интересно еще с точки зрения алгоритмов решение этой задачи, можешь глянуть вот [это](https://youtu.be/ijwbVxLMp58?t=177). Там есть решение в лоб, в одну строку, и решение с двумя указателями. Какое использовать решать тебе :)

2023-02-17 09:28 UTC, pavel-nyukalo commented on js/functions.js
> +findNumber('ECMAScript 2022');
Правильно понял, что ты реализовывал это?

![image](https://user-images.githubusercontent.com/52506235/219605437-5b43e8be-4d18-42bc-9edb-06c270b3890a.png)

В этом случае она должна вернуть 15

![image](https://user-images.githubusercontent.com/52506235/219605550-35bd11e1-a9fc-43d1-ae5d-5a1f81b4c9a6.png)

2023-02-17 09:43 UTC, Dante01Rus commented on js/functions.js
> +findNumber('ECMAScript 2022');
я думал тут вообще опечатка, дробное число 1.5. Оно у меня округляется и выводится целое число

2023-02-19 13:28 UTC, pavel-nyukalo approved these changes

2023-02-19 13:28 UTC, merged