реализована функция генерерирующая фото и опсание к нему с комментари…
htmlacademy-javascript/2180451-kekstagram-28 pull request #3
Opened 2023-02-23 09:08 UTC by Dante01Rus

…ямии

2023-02-25 15:37 UTC, pavel-nyukalo requested changes

2023-02-25 15:37 UTC, pavel-nyukalo commented on js/main.js
> +const generatedCommentId = getRandomValue(1, 1000);
По критерию, у нас для всех магических чисел нужны константы (`UPPER_CASE`)

2023-02-25 15:37 UTC, pavel-nyukalo commented on js/main.js
> +    avatar: `img/avatar-${getRandomInteger(1, 6)}.svg`,
Аналогично про магические значения. Конкретно здесь, это `MIN_AVATAR_COUNT` (как-нибудь так) и `MAX_...`

2023-02-25 15:37 UTC, pavel-nyukalo commented on js/main.js
> +    likes: getRandomInteger(15, 200),
+1 про магические

2023-02-25 15:37 UTC, pavel-nyukalo commented on js/main.js
> +const similarPhotoDescription = () => Array.from({length: 25}, photoDescription);
+1

2023-02-25 15:37 UTC, pavel-nyukalo commented on js/main.js
> +    name: `${NAMES[getRandomInteger(0, NAMES.length - 1)]}`
Не ошибка, но можно подумать в сторону функции, которая будет возвращать случайное число из переданного массива

2023-02-26 12:11 UTC, pavel-nyukalo requested changes

2023-02-26 12:11 UTC, pavel-nyukalo commented on js/main.js
> +const COMMENT_ID_MIN = 1; const COMMENT_ID_MAX = 1000;
Для читаемости я бы лучше писал на новых строках, а не по две константы в строчку

Если хочется именно показать связанность этих значений, то можно сделать объект-перечисление по типу (примеры есть в [Б8](https://up.htmlacademy.ru/javascript/28/criteries#b8))
```js
const Avatar = {
  MIN: 1,
  MAX: 6
}
```

2023-02-26 12:11 UTC, pavel-nyukalo commented on js/main.js
> +  const PREVIOUS_VALUE = [];
Думаю, здесь лучше оставить в `camelCase`, поскольку могут сослаться на критерий о том, что все, что названо в `UPPER_CASE` должно быть в начале файла до основного кода

2023-02-26 12:11 UTC, pavel-nyukalo commented on js/main.js
> +    id: COMMENT_ID(),
Тут так же думаю могут придраться к именованию, что функция в `UPPER_CASE`

![image](https://user-images.githubusercontent.com/52506235/221409659-e829c023-ca91-4000-a0e8-20643991de45.png)

![image](https://user-images.githubusercontent.com/52506235/221409673-fc400e22-02d2-4ee4-b035-1eae3259fd3b.png)

2023-02-26 12:11 UTC, pavel-nyukalo commented on js/main.js
> +const PHOTO_DESCRIPTIONS_ARRAY = () => Array.from({length: 25}, photoDescription);
25 тоже магическое число, надо в константы

2023-02-26 12:29 UTC, Dante01Rus commented on js/main.js
> +    id: COMMENT_ID(),
![Снимок экрана 2023-02-26 в 15 28 50](https://user-images.githubusercontent.com/109906292/221410540-c05acaf8-854e-42a1-bdd8-633c185459d4.png)
так как верно все-таки будет?)

2023-02-27 16:31 UTC, pavel-niukalo approved these changes

2023-02-27 16:31 UTC, merged