Отрисуй меня полностью
htmlacademy-javascript/2180451-kekstagram-28 pull request #5
Opened 2023-03-06 20:21 UTC by Dante01Rus

---
:mortar_board: [Отрисуй меня полностью](https://up.htmlacademy.ru/javascript/28/user/2180451/tasks/12)

:boom: https://htmlacademy-javascript.github.io/2180451-kekstagram-28/5/

2023-03-07 19:55 UTC, pavel-nyukalo requested changes

2023-03-07 19:55 UTC, pavel-nyukalo commented on index.html
> +  <script src="js/rendering.js" type="module"></script>
Поскольку `main.js` у нас модуль, и мы уже сделали задание по модуляции, то нужно чтобы точкой входа в приложение был только `main.js` (и к этому нужно привыкать, ибо webpack, vite работают именно так - они собирают все в один бандл, который мы и подключаем к странице)

2023-03-07 22:15 UTC, Dante01Rus commented on index.html
> +  <script src="js/rendering.js" type="module"></script>
<img width="1114" alt="Снимок экрана 2023-03-08 в 01 13 11" src="https://user-images.githubusercontent.com/109906292/223565644-e93f9669-d0c2-4752-b173-f103e9deb50f.png">
не совсем понятно, как мне результат работы rendering.js перенести в main, чтобы там изменения в разметку перенеслись? пока только на уме перенести туда весь код)

2023-03-08 08:44 UTC, pavel-nyukalo requested changes

2023-03-08 08:44 UTC, pavel-nyukalo commented on js/main.js
> +picContainer.append(similarDescriptionsFragment);
Я бы предложил в `createElements` передавать массив, по которому нужно пройтись (нам потом это при работе с сетью поможет)

И в `picContainer` вставлять тоже внутри `createElements`. Так мы сделаем связь модулей более чистой, не будет что в `main.js` нужны DOM-узлы и фрагмент, объявленные в `rendering` , а `rendering.js` не нужны данные, объявленные здесь

Получится как-то так
```js
main.js

import {photoDescriptionArray} from './data.js';
import {createElements} from './rendering.js';

const descriptionData = photoDescriptionArray();
createElements(descriptionData);
```

```js
rendering.js

const picContainer = document.querySelector('.pictures');
const picTemplate = document.querySelector('#picture').content.querySelector('.picture');
const similarDescriptionsFragment = document.createDocumentFragment();

export function createElements(descriptionData) {
  descriptionData.forEach((dataItem) => {
    const picElement = picTemplate.cloneNode(true);
    picElement.querySelector('.picture__img').src = dataItem.url;
    picElement.querySelector('.picture__likes').textContent = dataItem.likes;
    picElement.querySelector('.picture__comments').textContent = dataItem['comments'].length;
    similarDescriptionsFragment.append(picElement);
  });
  
  picContainer.append(similarDescriptionsFragment);
}
```

(кстати, когда импортируем что-то из модуля, то сам модуль выше импортировать нет смысл, то бишь вот так нет смысла писать
```js
import './data.js';
import {photoDescriptionArray} from './data.js';
```

тут можно просто импортнуть то что нужно
```js
import {photoDescriptionArray} from './data.js';
```
)

2023-03-08 08:54 UTC, Dante01Rus commented on js/main.js
> +picContainer.append(similarDescriptionsFragment);
👍

2023-03-08 09:19 UTC, pavel-nyukalo approved these changes

2023-03-08 09:19 UTC, merged